import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppLayout from "@/components/AppLayout";
import { ThemeProvider } from "@/components/ThemeProvider";
import { PlayerListContextProvider } from "@/context/PlayerListContext";
import { Toaster } from "@/components/ui/toaster";
import { AddPlayerDrawerContextProvider } from "@/context/AddPlayerDrawerContext";
import { CreateTeamSettingsContextProvider } from "@/context/CreateTeamSettingContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-background`}>
        <CreateTeamSettingsContextProvider>
          <PlayerListContextProvider>
            <AddPlayerDrawerContextProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                <AppLayout>
                  {children}
                  <Toaster />
                </AppLayout>
              </ThemeProvider>
            </AddPlayerDrawerContextProvider>
          </PlayerListContextProvider>
        </CreateTeamSettingsContextProvider>
      </body>
    </html>
  );
}
